### ISSUE TITLE
Error in compiling Gaffer 0.4.0

### ISSUE THREAD

**Issue by unclassified01** [GovernmentCommunicationsHeadquarters/Gaffer#390] opened 2016-09-04 18:31 UTC
When we try to compile Gaffer 0.4.0 with Maven we get the errors in the attached file:

[maven errors.txt](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/files/454054/maven.errors.txt)

**Comment by gaffer01** [comment] 2016-09-06 15:40
Could you provide more details? Checking out tag `gaffer2-0.4.0` and running `mvn clean install` doesn't produce that error for me. Which tag are you using? Which version of Java? Which version of maven?

**Comment by unclassified01** [comment] 2016-09-10 10:05
we used Maven 3.3.9 and Java SE Development Kit 8u101. At first we used Windows 7 as OS, and we get the previous errors, then we switched to Gffer 0.4.1, and get the same error, so we tried with Debian 8, and we get the following other errors:
[gaffer.graph.GraphTest.txt](https://github.com/GovernmentCommunicationsHeadquarters/Gaffer/files/465350/gaffer.graph.GraphTest.txt)
So, @unclassified02 solved commenting the function shouldConstructGraphFromSchemaFolderPath in the file Gaffer-gaffer2-0.4.1\gaffer-core\graph\src\test\java\gaffer\graph\GraphTest.java
Now it seems to work properly (we are testing it with an Accumulo cluster and we are getting no errors nor warnings)

**Comment by p013570** [comment] 2016-09-19 07:25
Looks like the error is caused by that test expecting the schema types to be iterated over in a particular order. However, the types are stored in a HashMap so the order will not be consistent.

We need to update the test and possibly others too to not rely on the ordering of the schema types. This basically means if we import and export a schema - the json types may not be in the same order.

Alternatively, it might be neater to just change the TypeDefinitions HashMap into something like a LinkedHashMap so order is preserved.

**Comment by p013570** [comment] 2016-09-22 15:34
This has been fixed as part of gh-427. The change has been merged into the develop branch and will be released soon.

**Closed by p013570** 2016-09-22 15:34 UTC
Labels: bug, p:normal
